workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /-skip$/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  auto_cancel:
    on_new_commit: interruptible

image: node:20

stages:
  - lint
  - build
  - test

lint:
  stage: lint
  script:
    - npm install --prefix Backend
    - node -e "import('./Backend/src/core/parser.js'); import('./Backend/src/core/automatas.js'); import('./Backend/src/core/encriptador.js'); import('./Backend/src/services/carService.js'); import('./Backend/src/services/auditService.js'); import('./Backend/src/services/transmisorService.js'); import('./Backend/src/ports/carPort.js'); import('./Backend/src/adapters/wsCarAdapter.js'); import('./Backend/src/protocol/commands.js')"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build:
  stage: build
  script:
    - npm install --prefix Backend
    - echo "Compilando proyecto..."
    - node -e "import('./Backend/server.js')"
    - node --check Frontend/js/app.js
    - node --check Frontend/js/views/transmitterView.js
    - node --check Frontend/js/views/receiverView.js
    - node --check simulador/esp32-simulator.js
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: test
  script:
    - npm install --prefix Backend
    - npm install --prefix simulador
    - npm test --prefix Backend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
